# Generated by Django 2.0.2 on 2018-04-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level_no',
        ),
        migrations.RemoveField(
            model_name='question',
            name='set_no',
        ),
    ]
