# Generated by Django 2.0.2 on 2018-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180426_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='set_no',
            field=models.IntegerField(default=0),
        ),
    ]
