# Generated by Django 2.0.2 on 2018-04-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='date_created',
        ),
    ]
